services:
  api:
    image: btc2api:${API_VERSION}
    ports:
      - "4431:${PORT}"
    volumes:
      - profileImage:/app/src/users/profileImage
    environment:
      - API_VERSION=${API_VERSION}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_DB_URI=${MONGO_DB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - |
        FIREBASE_KEY=${FIREBASE_KEY}
      - |
        SSL_CERT=${SSL_CERT}
      - |
        SSL_KEY=${SSL_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # restart commented out due to github secret/actions dependencies
    #restart: unless-stopped

volumes:
  profileImage:
    name: btc2api_profileImage
