name: Deploy to Production
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "."
          target: "~/docker"
          timeout: "30s"
          command_timeout: "2m"
          rm: true
          overwrite: true
          strip_components: 0
          debug: true
          capture_stdout: true

      - name: Build and Deploy
        uses: appleboy/ssh-action@v1
        env:
          PORT: ${{ secrets.PORT }}
          NODE_ENV: production
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
          SSL_CERT: ${{ secrets.SSL_CERT }}
          SSL_KEY: ${{ secrets.SSL_KEY }}
          PRODUCTION_URL: ${{ secrets.PRODUCTION_URL }}
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: PORT,NODE_ENV,MONGO_DB_URI,JWT_SECRET,FIREBASE_KEY,SSL_CERT,SSL_KEY,PRODUCTION_URL
          script: |
            cd ~/docker
            docker build -t btc2api .
            docker compose up -d
