name: Deploy to Production
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH and transfer files
        run: |
          # Setup SSH key
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # Add host key checking exceptions
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

          # Create tar file (excluding .git and node_modules)
          touch deploy.tar.gz
          tar --exclude='.git' --exclude='node_modules' -czf deploy.tar.gz .

          # Create target directory and transfer file
          ssh -i ~/.ssh/deploy_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOSTNAME }} "mkdir -p ~/docker/btc2-api-${{ secrets.API_VERSION }}"
          scp -i ~/.ssh/deploy_key deploy.tar.gz ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOSTNAME }}:~/docker/btc2-api-${{ secrets.API_VERSION }}/

          # Clean up local files
          rm deploy.tar.gz

      - name: Build and Deploy
        uses: appleboy/ssh-action@v1
        env:
          API_VERSION: ${{ secrets.API_VERSION }}
          PORT: ${{ secrets.PORT }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
          SSL_CERT: ${{ secrets.SSL_CERT }}
          SSL_KEY: ${{ secrets.SSL_KEY }}
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: API_VERSION,PORT,NODE_ENV,MONGO_DB_URI,JWT_SECRET,FIREBASE_KEY,SSL_CERT,SSL_KEY
          script: |
            cd ~/docker/btc2-api-${{ secrets.API_VERSION }}
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz
            docker build -t btc2api:${{ secrets.API_VERSION }} .

            docker compose down
            docker compose up -d --force-recreate

            # Optional: Remove any unused images to save disk space
            docker image prune -f
